package primero;

// Generated 18-feb-2026 9:29:12 by Hibernate Tools 3.4.0.CR1

/**
 * Alojamientos generated by hbm2java
 */
public class Alojamientos implements java.io.Serializable {

	private Integer referencia;
	private String nombre;
	private String poblacion;
	private String provincia;
	private byte capacidad;
	private Integer tipo;
	private String ubicacion;
	private Boolean alquilado;

	public Alojamientos() {
	}

	public Alojamientos(String nombre, String poblacion, String provincia,
			byte capacidad, String ubicacion) {
		this.nombre = nombre;
		this.poblacion = poblacion;
		this.provincia = provincia;
		this.capacidad = capacidad;
		this.ubicacion = ubicacion;
	}

	public Alojamientos(String nombre, String poblacion, String provincia,
			byte capacidad, Integer tipo, String ubicacion, Boolean alquilado) {
		this.nombre = nombre;
		this.poblacion = poblacion;
		this.provincia = provincia;
		this.capacidad = capacidad;
		this.tipo = tipo;
		this.ubicacion = ubicacion;
		this.alquilado = alquilado;
	}

	public Integer getReferencia() {
		return this.referencia;
	}

	public void setReferencia(Integer referencia) {
		this.referencia = referencia;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(String poblacion) {
		this.poblacion = poblacion;
	}

	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	public byte getCapacidad() {
		return this.capacidad;
	}

	public void setCapacidad(byte capacidad) {
		this.capacidad = capacidad;
	}

	public Integer getTipo() {
		return this.tipo;
	}

	public void setTipo(Integer tipo) {
		this.tipo = tipo;
	}

	public String getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}

	public Boolean getAlquilado() {
		return this.alquilado;
	}

	public void setAlquilado(Boolean alquilado) {
		this.alquilado = alquilado;
	}

}
