package primero;

// Generated 18-feb-2026 9:29:12 by Hibernate Tools 3.4.0.CR1

/**
 * Tipos generated by hbm2java
 */
public class Tipos implements java.io.Serializable {

	private int codigo;
	private String descripcion;

	public Tipos() {
	}

	public Tipos(int codigo) {
		this.codigo = codigo;
	}

	public Tipos(int codigo, String descripcion) {
		this.codigo = codigo;
		this.descripcion = descripcion;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
