/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Francisco Mejias
 * @revision Andy Jan
 */
public class FinalView extends javax.swing.JPanel {

    /**
     * Creates new form FinalView
     */
    public FinalView() {
        initComponents();
    }

    public void setMensajeFinal(int numAlojamientos, int numPersonas) {
        // Usamos etiquetas HTML para que el texto se ajuste solo
        String texto = "<html><body style='text-align: center;'>"
                + "Se han alquilado " + numAlojamientos + " alojamientos para un "
                + "total de " + numPersonas + " personas."
                + "</body></html>";


        labelCalcularAlquiler.setText(texto);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelRuralHome = new javax.swing.JLabel();
        labelFelizEstancia = new javax.swing.JLabel();
        labelCalcularAlquiler = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        labelRuralHome.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        labelRuralHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRuralHome.setText("RuralHome....");
        labelRuralHome.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 10, 1));
        add(labelRuralHome, java.awt.BorderLayout.PAGE_START);

        labelFelizEstancia.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        labelFelizEstancia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFelizEstancia.setText("Feliz estancia");
        labelFelizEstancia.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 10, 1));
        add(labelFelizEstancia, java.awt.BorderLayout.PAGE_END);

        labelCalcularAlquiler.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        labelCalcularAlquiler.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCalcularAlquiler.setText("a");
        labelCalcularAlquiler.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(labelCalcularAlquiler, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelCalcularAlquiler;
    private javax.swing.JLabel labelFelizEstancia;
    private javax.swing.JLabel labelRuralHome;
    // End of variables declaration//GEN-END:variables
}
