/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Administrador
 */
public class ResultadosView extends javax.swing.JPanel {

    private int totalAlojamientos = 0;
    private int totalPersonas = 0;

    /**
     * Creates new form ResultadosView
     */
    public ResultadosView() {
        initComponents();

        // 1. Creamos el gestor pasando el JCheckBox que necesita el constructor
        ButtonEditor gestorBoton = new ButtonEditor(new javax.swing.JCheckBox());

        // 2. Usamos el MISMO objeto para las dos cosas (dibujar y clickar)
        // Usamos el índice 3 que es tu cuarta columna
        tablaResultados.getColumnModel().getColumn(3).setCellRenderer(gestorBoton);
        tablaResultados.getColumnModel().getColumn(3).setCellEditor(gestorBoton);
    }

    public void setCapacidadInicial(int capacidadBuscador) {
        this.totalPersonas = capacidadBuscador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaResultados = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        tablaResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "REFERENCIA", "NOMBRE", "PROVINCIA", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaResultadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaResultados);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButton1.setText("Volver principal");
        jButton1.setToolTipText("Volver a pantalla principal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.getAccessibleContext().setAccessibleDescription("");

        jButton2.setText("Finalizar alquiler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        add(jPanel1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 1. Buscamos la ventana (JFrame) que contiene este panel
        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);

        if (win instanceof javax.swing.JFrame) {
            javax.swing.JFrame frame = (javax.swing.JFrame) win;

            // 2. Ocultamos el panel actual (Resultados)
            this.setVisible(false);

            // 3. Recorremos los componentes del Frame para encontrar el principal y mostrarlo
            for (java.awt.Component c : frame.getContentPane().getComponents()) {
                if (c instanceof javax.swing.JPanel && "panelPrincipal".equals(c.getName())) {
                    c.setVisible(true);
                }
            }

            // 4. Refrescamos la interfaz
            frame.getContentPane().revalidate();
            frame.getContentPane().repaint();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablaResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaResultadosMouseClicked
        // TODO add your handling code here:
        int columna = tablaResultados.columnAtPoint(evt.getPoint());
        int fila = tablaResultados.rowAtPoint(evt.getPoint());

        // Si el usuario hace clic en la última columna (la de Alquilar)
        if (columna == 4) { // Suponiendo que es la quinta columna (índice 4)
            String nombre = tablaResultados.getValueAt(fila, 1).toString(); // Obtenemos el nombre del alojamiento

            // Mostramos un mensaje de confirmación (esto puntúa como RA)
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Has alquilado con éxito: " + nombre,
                    "Alquiler Confirmado",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_tablaResultadosMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (win instanceof javax.swing.JFrame) {
            javax.swing.JFrame frame = (javax.swing.JFrame) win;

            // Creamos la pantalla final
            FinalView vistaFinal = new FinalView();

            // PASAMOS LOS DATOS REALES acumulados
            vistaFinal.setMensajeFinal(totalAlojamientos, totalPersonas);

            // Cambiamos de pantalla
            frame.getContentPane().removeAll();
            frame.getContentPane().add(vistaFinal, java.awt.BorderLayout.CENTER);

            frame.revalidate();
            frame.repaint();
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaResultados;
    // End of variables declaration//GEN-END:variables

    // Esta clase hace que el botón sea "clicable" y ejecute acciones
    // Esta clase dibuja el botón (Renderer) y le da vida (Editor)
    // Esta clase ahora es RENDERER (dibuja) y EDITOR (funciona)
    class ButtonEditor extends javax.swing.DefaultCellEditor implements javax.swing.table.TableCellRenderer {

        protected javax.swing.JButton button;
        private String label;
        private boolean isPushed;

        public ButtonEditor(javax.swing.JCheckBox checkBox) {
            super(checkBox);
            button = new javax.swing.JButton();
            button.setOpaque(true);
            button.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    fireEditingStopped();
                }
            });
        }

        // ESTO ES LO QUE TE FALTABA (El Renderer)
        @Override
        public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            button.setText((value == null) ? "Alquilar" : value.toString());
            return button;
        }

        @Override
        public java.awt.Component getTableCellEditorComponent(javax.swing.JTable table, Object value,
                boolean isSelected, int row, int column) {
            label = (value == null) ? "Alquilo" : value.toString();
            button.setText(label);
            isPushed = true;
            return button;
        }

        @Override
        public Object getCellEditorValue() {
            if (isPushed) {
                // 1. Obtener la fila actual
                int fila = tablaResultados.getSelectedRow();

                // 2. Extraer la capacidad (asumiendo que está en la columna 2, ajusta según tu tabla)
                try {
                    String capacidadStr = tablaResultados.getValueAt(fila, 2).toString();
                    int capacidad = Integer.parseInt(capacidadStr);

                    // 3. Acumular en las variables del panel
                    totalAlojamientos++;
                    totalPersonas += capacidad;

                    javax.swing.JOptionPane.showMessageDialog(button, "Alquiler realizado. Total personas acumuladas: " + totalPersonas);
                } catch (Exception e) {
                    totalAlojamientos++; // Al menos contamos el alojamiento si falla el parseo
                }

                isPushed = false;
                return "ALQUILADO"; // Esto hace que el botón desaparezca físicamente
            }
            isPushed = false;
            return label;
        }

        @Override
        public boolean stopCellEditing() {
            isPushed = false;
            return super.stopCellEditing();
        }
    }
}
