package POJO;
// Generated 16-feb-2026 13:57:46 by Hibernate Tools 3.2.1.GA



/**
 * Alojamientos generated by hbm2java
 */
public class Alojamientos  implements java.io.Serializable {


     private Integer referencia;
     private Tipos tipos;
     private String nombre;
     private String poblacion;
     private String provincia;
     private byte capacidad;
     private String ubicacion;
     private Boolean alquilado;

    public Alojamientos() {
    }

	
    public Alojamientos(String nombre, String poblacion, String provincia, byte capacidad, String ubicacion) {
        this.nombre = nombre;
        this.poblacion = poblacion;
        this.provincia = provincia;
        this.capacidad = capacidad;
        this.ubicacion = ubicacion;
    }
    public Alojamientos(Tipos tipos, String nombre, String poblacion, String provincia, byte capacidad, String ubicacion, Boolean alquilado) {
       this.tipos = tipos;
       this.nombre = nombre;
       this.poblacion = poblacion;
       this.provincia = provincia;
       this.capacidad = capacidad;
       this.ubicacion = ubicacion;
       this.alquilado = alquilado;
    }
   
    public Integer getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(Integer referencia) {
        this.referencia = referencia;
    }
    public Tipos getTipos() {
        return this.tipos;
    }
    
    public void setTipos(Tipos tipos) {
        this.tipos = tipos;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPoblacion() {
        return this.poblacion;
    }
    
    public void setPoblacion(String poblacion) {
        this.poblacion = poblacion;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public byte getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(byte capacidad) {
        this.capacidad = capacidad;
    }
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }
    public Boolean getAlquilado() {
        return this.alquilado;
    }
    
    public void setAlquilado(Boolean alquilado) {
        this.alquilado = alquilado;
    }




}


