package POJO;
// Generated 16-feb-2026 13:57:46 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tipos generated by hbm2java
 */
public class Tipos  implements java.io.Serializable {


     private int codigo;
     private String descripcion;
     private Set alojamientoses = new HashSet(0);

    public Tipos() {
    }

	
    public Tipos(int codigo) {
        this.codigo = codigo;
    }
    public Tipos(int codigo, String descripcion, Set alojamientoses) {
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.alojamientoses = alojamientoses;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getAlojamientoses() {
        return this.alojamientoses;
    }
    
    public void setAlojamientoses(Set alojamientoses) {
        this.alojamientoses = alojamientoses;
    }




}


